/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dataprojedeneme;

/**
 *
 * @author beyzakoc
 */
public class BilhanKocScores extends javax.swing.JFrame {
 private boolean isScoreTreeCreated = false;
    /**
     * Creates new form Scores
     */
    public BilhanKocScores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lowest_lb = new javax.swing.JTextField();
        highest_lb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        allScores_lb = new javax.swing.JTextArea();
        searchName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        lowest_lb.setBackground(new java.awt.Color(211, 192, 129));
        jPanel1.add(lowest_lb);
        lowest_lb.setBounds(220, 350, 200, 40);

        highest_lb.setEditable(false);
        highest_lb.setBackground(new java.awt.Color(211, 192, 129));
        jPanel1.add(highest_lb);
        highest_lb.setBounds(240, 300, 180, 40);

        allScores_lb.setBackground(new java.awt.Color(211, 192, 129));
        allScores_lb.setColumns(20);
        allScores_lb.setRows(5);
        jScrollPane1.setViewportView(allScores_lb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 340, 150);

        searchName.setBackground(new java.awt.Color(227, 211, 143));
        searchName.setForeground(new java.awt.Color(225, 193, 137));
        searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameActionPerformed(evt);
            }
        });
        jPanel1.add(searchName);
        searchName.setBounds(10, 50, 310, 40);

        jButton1.setBackground(new java.awt.Color(241, 217, 160));
        jButton1.setFont(new java.awt.Font("Luminari", 3, 20)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 50, 92, 40);

        jButton2.setBackground(new java.awt.Color(255, 233, 159));
        jButton2.setFont(new java.awt.Font("Luminari", 0, 18)); // NOI18N
        jButton2.setText("GO MAİN PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(120, 570, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/beyzakoc/data/scoreFrame.JPG")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 667);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       if (!isScoreTreeCreated) {
        BilhanKocFunctionsScore.createTree(); 
        BilhanKocFunctionsScore.inorderTraversal(BilhanKocFunctionsScore.root);
        BilhanKocFunctionsScore.findMinScore(BilhanKocFunctionsScore.root);
        BilhanKocFunctionsScore.findMaxScore(BilhanKocFunctionsScore.root);
        isScoreTreeCreated = true;
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

BilhanKocMain main = new BilhanKocMain();
allScores_lb.setText("");
main.setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BilhanKocScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BilhanKocScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BilhanKocScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BilhanKocScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BilhanKocScores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea allScores_lb;
    public static javax.swing.JTextField highest_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField lowest_lb;
    public static javax.swing.JTextField searchName;
    // End of variables declaration//GEN-END:variables
}
