/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dataprojedeneme;

import javax.swing.JTextField;

/**
 *
 * @author beyzakoc
 */
public class BilhanKocStartFrame extends javax.swing.JFrame {

    static int sayi;
    static String userName;

    /**
     * Creates new form startFrame
     */
    public BilhanKocStartFrame() {
        initComponents();

        setResizable(false);
        piriReis.setVisible(false);
        captainLaz.setVisible(false);
        seyyideHurra.setVisible(false);
        vahsiKelebek.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        username = new javax.swing.JTextField();
        vahsiKelebek = new javax.swing.JLabel();
        seyyideHurra = new javax.swing.JLabel();
        captainLaz = new javax.swing.JLabel();
        piriReis = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox<>();
        kurukafa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 555, -1, -1));

        username.setBackground(new java.awt.Color(229, 151, 69));
        username.setFont(new java.awt.Font("Luminari", 0, 24)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setToolTipText("");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 280, 30));

        vahsiKelebek.setFont(new java.awt.Font("Luminari", 0, 24)); // NOI18N
        vahsiKelebek.setIcon(new javax.swing.ImageIcon("/Users/beyzakoc/data/selim.png")); // NOI18N
        vahsiKelebek.setText("Vahsi Kelebek");
        getContentPane().add(vahsiKelebek, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 250, -1));

        seyyideHurra.setFont(new java.awt.Font("Luminari", 0, 24)); // NOI18N
        seyyideHurra.setIcon(new javax.swing.ImageIcon("/Users/beyzakoc/data/seyyide hurra.png")); // NOI18N
        seyyideHurra.setText("Seyyire Hurra");
        getContentPane().add(seyyideHurra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 260, 240));

        captainLaz.setFont(new java.awt.Font("Luminari", 0, 24)); // NOI18N
        captainLaz.setIcon(new javax.swing.ImageIcon("/Users/beyzakoc/data/captain laz.png")); // NOI18N
        captainLaz.setText("Captain Laz");
        getContentPane().add(captainLaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 240, 230));

        piriReis.setFont(new java.awt.Font("Luminari", 0, 24)); // NOI18N
        piriReis.setIcon(new javax.swing.ImageIcon("/Users/beyzakoc/data/piri reis.png")); // NOI18N
        piriReis.setText("Piri Reis");
        getContentPane().add(piriReis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 230, -1));

        jButton1.setBackground(new java.awt.Color(153, 102, 0));
        jButton1.setFont(new java.awt.Font("Luminari", 0, 18)); // NOI18N
        jButton1.setText("Start");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 100, 50));

        comboBox.setBackground(new java.awt.Color(153, 102, 0));
        comboBox.setFont(new java.awt.Font("Luminari", 0, 18)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Your Character", "Piri Reis", "Captain Laz", "Seyyide Hurra", "Vahşi Kelebek" }));
        comboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxİtemStateChanged(evt);
            }
        });
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 260, 40));

        kurukafa.setIcon(new javax.swing.ImageIcon("/Users/beyzakoc/data/kurukafa-fotor-bg-remover-20250425153155.png")); // NOI18N
        getContentPane().add(kurukafa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 210, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/beyzakoc/data/bilgi.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed

    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        BilhanKocLevel1Warning level1uyarı = new BilhanKocLevel1Warning();

        level1uyarı.setVisible(true);

        // Şu anki frame'i kapat
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxİtemStateChanged

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed

        int selectedIndex = comboBox.getSelectedIndex();
        sayi = selectedIndex;

        String kullanıcıadı = username.getText();
        userName = kullanıcıadı;

        // Seçilen öğeye göre görünürlük ayarlama
        kurukafa.setVisible(selectedIndex == 0);
        piriReis.setVisible(selectedIndex == 1);
        captainLaz.setVisible(selectedIndex == 2);
        seyyideHurra.setVisible(selectedIndex == 3);
        vahsiKelebek.setVisible(selectedIndex == 4);

        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BilhanKocStartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BilhanKocStartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BilhanKocStartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BilhanKocStartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BilhanKocStartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel captainLaz;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel kurukafa;
    private javax.swing.JLabel piriReis;
    private javax.swing.JLabel seyyideHurra;
    private javax.swing.JTextField username;
    private javax.swing.JLabel vahsiKelebek;
    // End of variables declaration//GEN-END:variables
}
